global:
  defaultStorageClass: hostpath
  postgresql:
    auth:
      postgresPassword: "dbpwx123"
      database: "poemsdb"
app:
  image:
    name: poem-generator:4-dev
    pullPolicy: IfNotPresent
  service:
    containerPort: 8080
    servicePort: 443
    ingress:
      host: poetrydb.local.test
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: local-ca-issuer
        cert-manager.io/common-name: poetrydb.local.test
        cert-manager.io/subject-organizations: Netconnections
        cert-manager.io/subject-organizationalunits: "Development,DevOps"
  env:
    ASPNETCORE_ENVIRONMENT: Development
    ASPNETCORE_URLS: http://+:8080
    DB_CONNECTION_STRING: "Host=poem-generator-db-hl;Port=5432;Database=poemsdb;Username=postgres;Password=dbpwx123;SSL Mode=Disable"
dependencies:
  postgresql:
    enabled: true
db:
  primary:
    persistence:
      size: 1Gi